### ISSUE TITLE
String comparison

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-mailtoy#4]
Use String's `equals` method to compare String.
https://github.com/OOP2018/coinpurse-mailtoy/blob/a1c63002762e275eb05540a70353780e26e5fe16/src/coinpurse/Coin.java#L60

**Comment by jbrucker** [comment]
You are STILL using == in Lab 4 code.

TAs are trying to help you.  Why don't you pay attention and learn?
